// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktlzfadrwckdbylsnymv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bHpmYWRyd2NrZGJ5bHNueW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjQwNjksImV4cCI6MjA2ODI0MDA2OX0.OeXKWEQj78Dk4rMeEf9i746hXengX-0fDkfAEKr1lPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});